[[language]]
name = "latex"
soft-wrap.enable = true
language-servers = [ "texlab", "ltex-ls-plus" ]

[language-server.texlab.config.texlab.build]
onSave = true
forwardSearchAfter = true

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:1:%f", "%p" ]
# executable = "/Applications/Skim.app/Contents/SharedSupport/displayline"
# args = ["-g", "-r", "%l", "%p", "%f"]

[language-server.texlab.config.texlab.chktex]
onEdit = true

[[language]]
name = "markdown"
# soft-wrap.enable = true
language-servers = ["markdown-oxide", "ltex-ls-plus"]
